name: Trigger AWS CodeBuild

on:
  push:
    branches: [ main ]
    paths: [ 'app/**' ]

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Trigger CodeBuild
      run: |
        BUILD_ID=$(aws codebuild start-build \
          --project-name fast-scaling-github-build \
          --query 'build.id' --output text)
        echo "CodeBuild started: $BUILD_ID"
        
        # 빌드 완료까지 대기
        aws codebuild batch-get-builds --ids $BUILD_ID \
          --query 'builds[0].buildStatus' --output text
